/*
Copyright © 2023 Ken'ichiro Oyama <k1lowxb@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
package cmd

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"

	"github.com/bmatcuk/doublestar/v4"
	"github.com/k1LoW/sqlc-go-one-or-fail/internal/rewriter"
	"github.com/k1LoW/sqlc-go-one-or-fail/version"
	"github.com/spf13/cobra"
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:     "sqlc-go-one-or-fail [FILE_PATTERN]",
	Short:   "modify the Go code generated by sqlc to fail if more than one record is retrieved in the ':one' command",
	Long:    `modify the Go code generated by sqlc to fail if more than one record is retrieved in the ':one' command.`,
	Args:    cobra.ExactArgs(1),
	Version: version.Version,
	RunE: func(cmd *cobra.Command, args []string) error {
		p := args[0]
		ctx := context.Background()
		if d, err := os.Stat(p); err == nil && d.IsDir() {
			p = filepath.Join(p, "*.go")
		}
		base, pattern := doublestar.SplitPattern(p)
		if err := doublestar.GlobWalk(os.DirFS(base), pattern, func(path string, d os.DirEntry) error {
			if d.IsDir() {
				return nil
			}
			if !strings.HasSuffix(d.Name(), ".go") {
				return nil
			}
			p := filepath.Join(base, path)
			buf := new(bytes.Buffer)
			if err := rewriter.Rewrite(ctx, p, buf); err != nil {
				return err
			}
			if err := os.WriteFile(p, buf.Bytes(), 0644); err != nil {
				return err
			}
			return nil
		}); err != nil {
			return err
		}
		return nil
	},
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func init() {
}
